### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by TorchwoodPL** [damian-pastorini/dwdgame#1]
I set up everything, create new account and when I try to login I get:
http://img.h-y.eu/pic/111543243781.png

**Comment by damian-pastorini** [comment]
Hi @TorchwoodPL , sorry the delay on the response I've been far from the project the last two months but I'm planning on continue with it over this month.
Did you were able to fix your issue? I can't see the attached screenshot, could you just copy/paste the error text if the error persist please?
Thanks for report!
Best,

**Comment by damian-pastorini** [comment]
I'm closing the ticket since is really old, please open a new one if the problem persist.
Thanks!
